"""Generate the Claude Code, MCP and bundle files derived from the configuration."""

from __future__ import annotations

import json
import shlex
from collections.abc import Mapping
from pathlib import Path
from typing import Any

import yaml

from . import guardrails, team
from .config import LAYERS, ConfigError, load_roles, load_versions
from .paths import FRAMEWORK_DIR, ProjectPaths

MCP_SERVER_NAME = "databricks"
DF_HELPER_PERMISSION = "Bash(bash .deltaforce/bin/df *)"
MCP_STARTUP_TIMEOUT_MS = "60000"  # the MCP server's first start on Windows can exceed the default
STATUSLINE_SCRIPT = FRAMEWORK_DIR / "lib" / "monitor" / "statusline.sh"
STATUSLINE_REFRESH_SECONDS = 15  # keeps the line current while the session is idle and agents work
CLAUDE_MD_START = "<!-- deltaforce:project-context:start -->"
CLAUDE_MD_END = "<!-- deltaforce:project-context:end -->"
GITIGNORE_START = "# deltaforce:start"
GITIGNORE_END = "# deltaforce:end"

GITIGNORE_ENTRIES = (
    ".deltaforce/framework/",
    ".deltaforce/review/",
    ".deltaforce/bin/",
    ".deltaforce/runtime/",
    ".deltaforce/.databrickscfg",
    ".deltaforce/status.json",
    ".deltaforce/audit.jsonl",
    ".mcp.json",
    ".claude/settings.local.json",
    ".claude/worktrees/",
    ".databricks/",
)

GENERATED_HEADER = "# Generated by DeltaForce AI from .deltaforce/config.yaml — re-run the installer instead of editing.\n"
NEW_CLAUDE_MD = (
    "# CLAUDE.md\n\n"
    "This file provides guidance to Claude Code (claude.ai/code) when working with code in this repository.\n"
)


def _posix(path: Path) -> str:
    return path.resolve().as_posix()


def _load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8").strip()
    if not text:
        return {}
    try:
        return json.loads(text)
    except json.JSONDecodeError as exc:
        raise ConfigError(f"{path} is not valid JSON ({exc}) — fix or remove it, then re-run") from exc


def _write_text(path: Path, text: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    return path


def _write_json(path: Path, data: Mapping[str, Any]) -> Path:
    return _write_text(path, json.dumps(data, indent=2, ensure_ascii=False) + "\n")


def replace_block(text: str, start: str, end: str, body: str) -> str:
    """Replace the managed block between the markers, or append it."""
    managed = f"{start}\n{body.rstrip()}\n{end}"
    if start in text and end in text:
        before, rest = text.split(start, 1)
        _, after = rest.split(end, 1)
        return f"{before}{managed}{after}"
    if not text.strip():
        return managed + "\n"
    return text.rstrip("\n") + "\n\n" + managed + "\n"


def medallion_variables(dev: Mapping[str, Any]) -> dict[str, str]:
    medallion = dev["medallion"]
    if medallion["layout"] == "single_schema":
        schemas = {layer: medallion["schema"] for layer in LAYERS}
        prefixes = {layer: f"{layer}_" for layer in LAYERS}
    else:
        schemas = {layer: medallion[layer] for layer in LAYERS}
        prefixes = {layer: "" for layer in LAYERS}
    return {
        **{f"schema_{layer}": schemas[layer] for layer in LAYERS},
        **{f"prefix_{layer}": prefixes[layer] for layer in LAYERS},
    }


def medallion_schemas(dev: Mapping[str, Any]) -> list[str]:
    variables = medallion_variables(dev)
    return list(dict.fromkeys(variables[f"schema_{layer}"] for layer in LAYERS))


def databricks_env(config: Mapping[str, Any], paths: ProjectPaths) -> dict[str, str]:
    return {
        "DATABRICKS_CONFIG_FILE": _posix(paths.databricks_cfg),
        "DATABRICKS_CONFIG_PROFILE": config["databricks"]["profile"],
    }


def write_mcp_json(config: Mapping[str, Any], paths: ProjectPaths) -> Path:
    # Machine-specific (absolute paths): gitignored and regenerated by every installer run.
    data = _load_json(paths.mcp_json)
    servers = data.setdefault("mcpServers", {})
    servers[MCP_SERVER_NAME] = {
        "command": _posix(paths.venv_python),
        "args": [_posix(paths.mcp_entry)],
        "env": databricks_env(config, paths),
    }
    prod = config.get("prod")
    if prod:
        # Same server code, bound to the production profile; hooks keep it read-only.
        servers[guardrails.PROD_MCP_SERVER] = {
            "command": _posix(paths.venv_python),
            "args": [_posix(paths.mcp_entry)],
            "env": {"DATABRICKS_CONFIG_FILE": _posix(paths.databricks_cfg), "DATABRICKS_CONFIG_PROFILE": prod["profile"]},
        }
    else:
        servers.pop(guardrails.PROD_MCP_SERVER, None)
    return _write_json(paths.mcp_json, data)


def write_claude_settings(config: Mapping[str, Any], paths: ProjectPaths) -> Path:
    data = _load_json(paths.claude_settings)
    env = data.setdefault("env", {})
    env["CLAUDE_CODE_MAX_SUBAGENT_SPAWN_DEPTH"] = str(config["team"]["max_spawn_depth"])
    env["CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS"] = "0"
    # Subagent worktrees must branch from the checked-out feature branch, not from main.
    data.setdefault("worktree", {})["baseRef"] = "head"
    env["MCP_TIMEOUT"] = MCP_STARTUP_TIMEOUT_MS
    enabled = data.setdefault("enabledMcpjsonServers", [])
    enabled[:] = [name for name in enabled if name != guardrails.PROD_MCP_SERVER or config.get("prod")]
    for name in [MCP_SERVER_NAME] + ([guardrails.PROD_MCP_SERVER] if config.get("prod") else []):
        if name not in enabled:
            enabled.append(name)
    # Every session in the project starts as the DeltaForce Project Manager.
    data["agent"] = "pm"
    permissions = data.setdefault("permissions", {})
    allow = permissions.setdefault("allow", [])
    if DF_HELPER_PERMISSION not in allow:
        allow.append(DF_HELPER_PERMISSION)
    # Deny rules hold even if a hook fails; keep the user's own rules.
    kept = [rule for rule in permissions.get("deny", []) if not guardrails.is_managed_deny_rule(rule)]
    permissions["deny"] = kept + guardrails.static_deny_rules(config)
    return _write_json(paths.claude_settings, data)


def write_claude_settings_local(config: Mapping[str, Any], paths: ProjectPaths) -> Path:
    # Makes every Bash call in the session (databricks CLI included) use the project profile.
    data = _load_json(paths.claude_settings_local)
    env = data.setdefault("env", {})
    env.update(databricks_env(config, paths))
    # Agents in worktrees reach the main checkout's tools through $DF_ROOT.
    env["DF_ROOT"] = _posix(paths.root)
    # Guardrail and audit hooks use machine-specific interpreter paths, so they live in the local settings.
    data["hooks"] = guardrails.merge_hooks(data.get("hooks"), paths)
    # The status line links the monitor without calling the model; a status line of the user's own is kept.
    if not data.get("statusLine") or is_deltaforce_statusline(data["statusLine"]):
        data["statusLine"] = {
            "type": "command",
            "command": statusline_command(paths),
            "refreshInterval": STATUSLINE_REFRESH_SECONDS,
        }
    return _write_json(paths.claude_settings_local, data)


def statusline_command(paths: ProjectPaths) -> str:
    # Claude Code runs the status line in a shell (Git Bash on Windows). Sourcing the script keeps it to that
    # one process: on Windows each extra process adds a second or more to every refresh.
    return f'. "{_posix(STATUSLINE_SCRIPT)}" "{_posix(paths.root)}" "{_posix(paths.venv_python)}"'


def is_deltaforce_statusline(value: Any) -> bool:
    return STATUSLINE_SCRIPT.name in json.dumps(value)


def write_guard_policy(config: Mapping[str, Any], paths: ProjectPaths) -> Path:
    return _write_json(paths.guard_policy, guardrails.build_policy(config, paths, load_roles()))


def write_df_wrapper(_: Mapping[str, Any], paths: ProjectPaths) -> Path:
    versions = load_versions()

    def quote(path: Path) -> str:
        return shlex.quote(_posix(path))

    script = f"""#!/usr/bin/env bash
# DeltaForce helper: bash .deltaforce/bin/df <event|validate|doctor> ...
# Generated by the installer for this machine; not committed.
set -euo pipefail
export UV_PYTHON_INSTALL_DIR={quote(paths.runtime / "python")} UV_CACHE_DIR={quote(paths.runtime / "uv-cache")}
export UV_PYTHON_PREFERENCE=only-managed UV_NO_CONFIG=1 UV_LINK_MODE=copy PYTHONUTF8=1
exec {quote(paths.uv)} run --quiet --no-project --python {versions["DF_PYTHON_VERSION"]} --with pyyaml --with jsonschema \\
    python {quote(FRAMEWORK_DIR / "lib" / "py" / "dfcli.py")} --target {quote(paths.root)} "$@"
"""
    return _write_text(paths.df_wrapper, script)


def render_project_context(config: Mapping[str, Any]) -> str:
    project, db = config["project"], config["databricks"]
    dev = config["targets"]["dev"]
    medallion = dev["medallion"]
    variables = medallion_variables(dev)

    if medallion["layout"] == "single_schema":
        layout = f"single schema `{medallion['schema']}`, table names prefixed `bronze_`, `silver_`, `gold_`"
    else:
        layout = ", ".join(f"{layer} `{medallion[layer]}`" for layer in LAYERS)
    compute = "serverless" if db["compute"] == "serverless" else f"cluster `{db['cluster_id']}`"
    protected = ", ".join(f"`{branch}`" for branch in project["protected_branches"])
    bundle_vars = ", ".join(f"`${{var.{name}}}`" for name in ("catalog", "warehouse_id", *variables))

    prod = config.get("prod")
    prod_row = (
        f"\n| Production (read-only) | {prod['host']} — MCP server `{guardrails.PROD_MCP_SERVER}`, warehouse "
        f"`{prod['warehouse_id']}`: queries, model and vector search calls, Genie and table stats only |"
        if prod
        else ""
    )

    return f"""## DeltaForce project context

Generated from `.deltaforce/config.yaml` by the DeltaForce installer. Change the configuration by re-running the installer, not by editing this block.

| Setting | Value |
|---|---|
| Project | `{project['name']}` |
| Workspace | {db['host']} |
| Databricks CLI | `"$DF_ROOT/.deltaforce/bin/databricks"` — profile `{db['profile']}` is preselected through the environment |
| Team | Sessions start as the PM; PO commands `/df-kickoff`, `/df-status`, `/df-approve`, `/df-changes`, `/df-conventions` |
| Client conventions | `.deltaforce/conventions.yaml` |{prod_row}
| SQL warehouse | `{db['warehouse_id']}` |
| Compute | {compute} |
| Dev catalog | `{dev['catalog']}` |
| Medallion layout | {layout} |
| Dev branch | `{project['dev_branch']}` |
| Protected branches | {protected} — never push to them |

- In source code and bundle resources, reference these values only through bundle variables ({bundle_vars}); never write catalog, schema or table names literally.
- The schemas above are the starting point, not a limit: create the schemas and tables the solution needs inside the dev catalog, keep them consistent with the architecture in `.deltaforce/architecture/` and the medallion layers, and declare them in the bundle with variables.
- When calling Databricks MCP tools directly (exploration, validation), pass the dev catalog and schemas above explicitly.
- Every Databricks resource (jobs, pipelines, schemas, volumes, dashboards, apps, endpoints, indexes, …) is declared in the asset bundle and deployed by the DevOps Engineer; MCP tools are for reading, querying and running only.
- DeltaForce guardrails (hooks) block resource changes outside the bundle, writes outside the dev catalog, any non-read activity on production, bundle deploys outside the dev target or by roles other than the DevOps Engineer, pushes to protected branches and history rewrites. A blocked action returns `DeltaForce guardrail: <reason>`: report it, never work around it.
"""


def write_claude_md(config: Mapping[str, Any], paths: ProjectPaths) -> Path:
    text = paths.claude_md.read_text(encoding="utf-8") if paths.claude_md.exists() else NEW_CLAUDE_MD
    return _write_text(
        paths.claude_md, replace_block(text, CLAUDE_MD_START, CLAUDE_MD_END, render_project_context(config))
    )


def write_gitignore(_: Mapping[str, Any], paths: ProjectPaths) -> Path:
    text = paths.gitignore.read_text(encoding="utf-8") if paths.gitignore.exists() else ""
    body = "# DeltaForce AI: machine-specific files and secrets\n" + "\n".join(GITIGNORE_ENTRIES)
    return _write_text(paths.gitignore, replace_block(text, GITIGNORE_START, GITIGNORE_END, body))


def write_bundle(config: Mapping[str, Any], paths: ProjectPaths) -> list[Path]:
    project, db = config["project"], config["databricks"]
    dev = config["targets"]["dev"]
    written = []

    if not paths.bundle.exists():
        bundle = {
            "bundle": {"name": project["name"]},
            "include": ["resources/*.yml"],
            "targets": {
                "dev": {"mode": "development", "default": True, "workspace": {"host": db["host"]}},
                "prod": {"mode": "production"},
            },
        }
        header = (
            "# Databricks Asset Bundle. Created once by DeltaForce AI; owned by the project from now on.\n"
            "# prod: workspace host, run_as and variable values are injected by CI/CD (BUNDLE_VAR_<name>).\n"
        )
        written.append(_write_text(paths.bundle, header + yaml.safe_dump(bundle, sort_keys=False)))

    variables = medallion_variables(dev)
    descriptions = {
        "catalog": "Unity Catalog catalog",
        "warehouse_id": "SQL warehouse ID",
        **{f"schema_{layer}": f"Schema of the {layer} layer" for layer in LAYERS},
        **{f"prefix_{layer}": f"Table name prefix of the {layer} layer" for layer in LAYERS},
    }
    document = {
        "variables": {
            # Only layout prefixes get defaults: environment values must be set per target,
            # so a prod deployment without CI/CD values fails instead of writing to dev.
            name: {"description": text, "default": variables[name]} if name.startswith("prefix_") else {"description": text}
            for name, text in descriptions.items()
        },
        "targets": {
            "dev": {
                "variables": {
                    "catalog": dev["catalog"],
                    "warehouse_id": db["warehouse_id"],
                    **{name: value for name, value in variables.items() if name.startswith("schema_")},
                }
            }
        },
    }
    written.append(_write_text(paths.bundle_variables, GENERATED_HEADER + yaml.safe_dump(document, sort_keys=False)))
    return written


def generate_all(config: Mapping[str, Any], paths: ProjectPaths) -> list[str]:
    written = [
        write_mcp_json(config, paths),
        write_claude_settings(config, paths),
        write_claude_settings_local(config, paths),
        write_claude_md(config, paths),
        write_gitignore(config, paths),
        write_df_wrapper(config, paths),
        write_guard_policy(config, paths),
        *write_bundle(config, paths),
    ]
    return [path.relative_to(paths.root).as_posix() for path in written] + team.install_team(config, paths)
