"""Generate the Claude Code, MCP and bundle files derived from the configuration."""

from __future__ import annotations

import json
from collections.abc import Mapping
from pathlib import Path
from typing import Any

import yaml

from .config import LAYERS, ConfigError
from .paths import ProjectPaths

MCP_SERVER_NAME = "databricks"
CLAUDE_MD_START = "<!-- deltaforce:project-context:start -->"
CLAUDE_MD_END = "<!-- deltaforce:project-context:end -->"
GITIGNORE_START = "# deltaforce:start"
GITIGNORE_END = "# deltaforce:end"

GITIGNORE_ENTRIES = (
    ".deltaforce/framework/",
    ".deltaforce/bin/",
    ".deltaforce/runtime/",
    ".deltaforce/.databrickscfg",
    ".deltaforce/status.json",
    ".mcp.json",
    ".claude/settings.local.json",
    ".claude/worktrees/",
    ".databricks/",
)

GENERATED_HEADER = "# Generated by DeltaForce AI from .deltaforce/config.yaml — re-run the installer instead of editing.\n"
NEW_CLAUDE_MD = (
    "# CLAUDE.md\n\n"
    "This file provides guidance to Claude Code (claude.ai/code) when working with code in this repository.\n"
)


def _posix(path: Path) -> str:
    return path.resolve().as_posix()


def _load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8").strip()
    if not text:
        return {}
    try:
        return json.loads(text)
    except json.JSONDecodeError as exc:
        raise ConfigError(f"{path} is not valid JSON ({exc}) — fix or remove it, then re-run") from exc


def _write_text(path: Path, text: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def _write_json(path: Path, data: Mapping[str, Any]) -> Path:
    return _write_text(path, json.dumps(data, indent=2, ensure_ascii=False) + "\n")


def replace_block(text: str, start: str, end: str, body: str) -> str:
    """Replace the managed block between the markers, or append it."""
    managed = f"{start}\n{body.rstrip()}\n{end}"
    if start in text and end in text:
        before, rest = text.split(start, 1)
        _, after = rest.split(end, 1)
        return f"{before}{managed}{after}"
    if not text.strip():
        return managed + "\n"
    return text.rstrip("\n") + "\n\n" + managed + "\n"


def medallion_variables(dev: Mapping[str, Any]) -> dict[str, str]:
    medallion = dev["medallion"]
    if medallion["layout"] == "single_schema":
        schemas = {layer: medallion["schema"] for layer in LAYERS}
        prefixes = {layer: f"{layer}_" for layer in LAYERS}
    else:
        schemas = {layer: medallion[layer] for layer in LAYERS}
        prefixes = {layer: "" for layer in LAYERS}
    return {
        **{f"schema_{layer}": schemas[layer] for layer in LAYERS},
        **{f"prefix_{layer}": prefixes[layer] for layer in LAYERS},
    }


def medallion_schemas(dev: Mapping[str, Any]) -> list[str]:
    variables = medallion_variables(dev)
    return list(dict.fromkeys(variables[f"schema_{layer}"] for layer in LAYERS))


def databricks_env(config: Mapping[str, Any], paths: ProjectPaths) -> dict[str, str]:
    return {
        "DATABRICKS_CONFIG_FILE": _posix(paths.databricks_cfg),
        "DATABRICKS_CONFIG_PROFILE": config["databricks"]["profile"],
    }


def write_mcp_json(config: Mapping[str, Any], paths: ProjectPaths) -> Path:
    # Machine-specific (absolute paths): gitignored and regenerated by every installer run.
    data = _load_json(paths.mcp_json)
    data.setdefault("mcpServers", {})[MCP_SERVER_NAME] = {
        "command": _posix(paths.venv_python),
        "args": [_posix(paths.mcp_entry)],
        "env": databricks_env(config, paths),
    }
    return _write_json(paths.mcp_json, data)


def write_claude_settings(config: Mapping[str, Any], paths: ProjectPaths) -> Path:
    data = _load_json(paths.claude_settings)
    env = data.setdefault("env", {})
    env["CLAUDE_CODE_MAX_SUBAGENT_SPAWN_DEPTH"] = str(config["team"]["max_spawn_depth"])
    env["CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS"] = "0"
    # Subagent worktrees must branch from the checked-out feature branch, not from main.
    data.setdefault("worktree", {})["baseRef"] = "head"
    enabled = data.setdefault("enabledMcpjsonServers", [])
    if MCP_SERVER_NAME not in enabled:
        enabled.append(MCP_SERVER_NAME)
    return _write_json(paths.claude_settings, data)


def write_claude_settings_local(config: Mapping[str, Any], paths: ProjectPaths) -> Path:
    # Makes every Bash call in the session (databricks CLI included) use the project profile.
    data = _load_json(paths.claude_settings_local)
    data.setdefault("env", {}).update(databricks_env(config, paths))
    return _write_json(paths.claude_settings_local, data)


def render_project_context(config: Mapping[str, Any]) -> str:
    project, db = config["project"], config["databricks"]
    dev = config["targets"]["dev"]
    medallion = dev["medallion"]
    variables = medallion_variables(dev)

    if medallion["layout"] == "single_schema":
        layout = f"single schema `{medallion['schema']}`, table names prefixed `bronze_`, `silver_`, `gold_`"
    else:
        layout = ", ".join(f"{layer} `{medallion[layer]}`" for layer in LAYERS)
    compute = "serverless" if db["compute"] == "serverless" else f"cluster `{db['cluster_id']}`"
    protected = ", ".join(f"`{branch}`" for branch in project["protected_branches"])
    bundle_vars = ", ".join(f"`${{var.{name}}}`" for name in ("catalog", "warehouse_id", *variables))

    return f"""## DeltaForce project context

Generated from `.deltaforce/config.yaml` by the DeltaForce installer. Change the configuration by re-running the installer, not by editing this block.

| Setting | Value |
|---|---|
| Project | `{project['name']}` |
| Workspace | {db['host']} |
| Databricks CLI | `.deltaforce/bin/databricks` — profile `{db['profile']}` is preselected through the environment |
| SQL warehouse | `{db['warehouse_id']}` |
| Compute | {compute} |
| Dev catalog | `{dev['catalog']}` |
| Medallion layout | {layout} |
| Dev branch | `{project['dev_branch']}` |
| Protected branches | {protected} — never push to them |

- In source code and bundle resources, reference these values only through bundle variables ({bundle_vars}); never write catalog, schema or table names literally.
- When calling Databricks MCP tools directly (exploration, validation), pass the dev catalog and schemas above explicitly.
"""


def write_claude_md(config: Mapping[str, Any], paths: ProjectPaths) -> Path:
    text = paths.claude_md.read_text(encoding="utf-8") if paths.claude_md.exists() else NEW_CLAUDE_MD
    return _write_text(
        paths.claude_md, replace_block(text, CLAUDE_MD_START, CLAUDE_MD_END, render_project_context(config))
    )


def write_gitignore(_: Mapping[str, Any], paths: ProjectPaths) -> Path:
    text = paths.gitignore.read_text(encoding="utf-8") if paths.gitignore.exists() else ""
    body = "# DeltaForce AI: machine-specific files and secrets\n" + "\n".join(GITIGNORE_ENTRIES)
    return _write_text(paths.gitignore, replace_block(text, GITIGNORE_START, GITIGNORE_END, body))


def write_bundle(config: Mapping[str, Any], paths: ProjectPaths) -> list[Path]:
    project, db = config["project"], config["databricks"]
    dev = config["targets"]["dev"]
    written = []

    if not paths.bundle.exists():
        bundle = {
            "bundle": {"name": project["name"]},
            "include": ["resources/*.yml"],
            "targets": {
                "dev": {"mode": "development", "default": True, "workspace": {"host": db["host"]}},
                "prod": {"mode": "production"},
            },
        }
        header = (
            "# Databricks Asset Bundle. Created once by DeltaForce AI; owned by the project from now on.\n"
            "# prod: workspace host, run_as and variable values are injected by CI/CD (BUNDLE_VAR_<name>).\n"
        )
        written.append(_write_text(paths.bundle, header + yaml.safe_dump(bundle, sort_keys=False)))

    variables = medallion_variables(dev)
    descriptions = {
        "catalog": "Unity Catalog catalog",
        "warehouse_id": "SQL warehouse ID",
        **{f"schema_{layer}": f"Schema of the {layer} layer" for layer in LAYERS},
        **{f"prefix_{layer}": f"Table name prefix of the {layer} layer" for layer in LAYERS},
    }
    document = {
        "variables": {
            # Only layout prefixes get defaults: environment values must be set per target,
            # so a prod deployment without CI/CD values fails instead of writing to dev.
            name: {"description": text, "default": variables[name]} if name.startswith("prefix_") else {"description": text}
            for name, text in descriptions.items()
        },
        "targets": {
            "dev": {
                "variables": {
                    "catalog": dev["catalog"],
                    "warehouse_id": db["warehouse_id"],
                    **{name: value for name, value in variables.items() if name.startswith("schema_")},
                }
            }
        },
    }
    written.append(_write_text(paths.bundle_variables, GENERATED_HEADER + yaml.safe_dump(document, sort_keys=False)))
    return written


def generate_all(config: Mapping[str, Any], paths: ProjectPaths) -> list[str]:
    written = [
        write_mcp_json(config, paths),
        write_claude_settings(config, paths),
        write_claude_settings_local(config, paths),
        write_claude_md(config, paths),
        write_gitignore(config, paths),
        *write_bundle(config, paths),
    ]
    return [path.relative_to(paths.root).as_posix() for path in written]
